/*
SSOT API

This page describes the api endpoints for single source of truth infra project

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ServerInfoSystemInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServerInfoSystemInfo{}

// ServerInfoSystemInfo struct for ServerInfoSystemInfo
type ServerInfoSystemInfo struct {
	Environment *string `json:"environment,omitempty"`
	Version *string `json:"version,omitempty"`
}

// NewServerInfoSystemInfo instantiates a new ServerInfoSystemInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServerInfoSystemInfo() *ServerInfoSystemInfo {
	this := ServerInfoSystemInfo{}
	return &this
}

// NewServerInfoSystemInfoWithDefaults instantiates a new ServerInfoSystemInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServerInfoSystemInfoWithDefaults() *ServerInfoSystemInfo {
	this := ServerInfoSystemInfo{}
	return &this
}

// GetEnvironment returns the Environment field value if set, zero value otherwise.
func (o *ServerInfoSystemInfo) GetEnvironment() string {
	if o == nil || IsNil(o.Environment) {
		var ret string
		return ret
	}
	return *o.Environment
}

// GetEnvironmentOk returns a tuple with the Environment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerInfoSystemInfo) GetEnvironmentOk() (*string, bool) {
	if o == nil || IsNil(o.Environment) {
		return nil, false
	}
	return o.Environment, true
}

// HasEnvironment returns a boolean if a field has been set.
func (o *ServerInfoSystemInfo) HasEnvironment() bool {
	if o != nil && !IsNil(o.Environment) {
		return true
	}

	return false
}

// SetEnvironment gets a reference to the given string and assigns it to the Environment field.
func (o *ServerInfoSystemInfo) SetEnvironment(v string) {
	o.Environment = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *ServerInfoSystemInfo) GetVersion() string {
	if o == nil || IsNil(o.Version) {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerInfoSystemInfo) GetVersionOk() (*string, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *ServerInfoSystemInfo) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *ServerInfoSystemInfo) SetVersion(v string) {
	o.Version = &v
}

func (o ServerInfoSystemInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServerInfoSystemInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Environment) {
		toSerialize["environment"] = o.Environment
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	return toSerialize, nil
}

type NullableServerInfoSystemInfo struct {
	value *ServerInfoSystemInfo
	isSet bool
}

func (v NullableServerInfoSystemInfo) Get() *ServerInfoSystemInfo {
	return v.value
}

func (v *NullableServerInfoSystemInfo) Set(val *ServerInfoSystemInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableServerInfoSystemInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableServerInfoSystemInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServerInfoSystemInfo(val *ServerInfoSystemInfo) *NullableServerInfoSystemInfo {
	return &NullableServerInfoSystemInfo{value: val, isSet: true}
}

func (v NullableServerInfoSystemInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServerInfoSystemInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


