/*
SSOT API

This page describes the api endpoints for single source of truth infra project

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the Virtualization type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Virtualization{}

// Virtualization struct for Virtualization
type Virtualization struct {
	Type *string `json:"type,omitempty"`
}

// NewVirtualization instantiates a new Virtualization object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVirtualization() *Virtualization {
	this := Virtualization{}
	return &this
}

// NewVirtualizationWithDefaults instantiates a new Virtualization object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVirtualizationWithDefaults() *Virtualization {
	this := Virtualization{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *Virtualization) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Virtualization) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *Virtualization) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *Virtualization) SetType(v string) {
	o.Type = &v
}

func (o Virtualization) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Virtualization) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

type NullableVirtualization struct {
	value *Virtualization
	isSet bool
}

func (v NullableVirtualization) Get() *Virtualization {
	return v.value
}

func (v *NullableVirtualization) Set(val *Virtualization) {
	v.value = val
	v.isSet = true
}

func (v NullableVirtualization) IsSet() bool {
	return v.isSet
}

func (v *NullableVirtualization) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVirtualization(val *Virtualization) *NullableVirtualization {
	return &NullableVirtualization{value: val, isSet: true}
}

func (v NullableVirtualization) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVirtualization) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


