/*
SSOT API

This page describes the api endpoints for single source of truth infra project

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the Motherboard type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Motherboard{}

// Motherboard struct for Motherboard
type Motherboard struct {
	Vendor *string `json:"vendor,omitempty"`
	Name *string `json:"name,omitempty"`
	SerialNumber *string `json:"serial_number,omitempty"`
}

// NewMotherboard instantiates a new Motherboard object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMotherboard() *Motherboard {
	this := Motherboard{}
	return &this
}

// NewMotherboardWithDefaults instantiates a new Motherboard object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMotherboardWithDefaults() *Motherboard {
	this := Motherboard{}
	return &this
}

// GetVendor returns the Vendor field value if set, zero value otherwise.
func (o *Motherboard) GetVendor() string {
	if o == nil || IsNil(o.Vendor) {
		var ret string
		return ret
	}
	return *o.Vendor
}

// GetVendorOk returns a tuple with the Vendor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Motherboard) GetVendorOk() (*string, bool) {
	if o == nil || IsNil(o.Vendor) {
		return nil, false
	}
	return o.Vendor, true
}

// HasVendor returns a boolean if a field has been set.
func (o *Motherboard) HasVendor() bool {
	if o != nil && !IsNil(o.Vendor) {
		return true
	}

	return false
}

// SetVendor gets a reference to the given string and assigns it to the Vendor field.
func (o *Motherboard) SetVendor(v string) {
	o.Vendor = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *Motherboard) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Motherboard) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *Motherboard) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *Motherboard) SetName(v string) {
	o.Name = &v
}

// GetSerialNumber returns the SerialNumber field value if set, zero value otherwise.
func (o *Motherboard) GetSerialNumber() string {
	if o == nil || IsNil(o.SerialNumber) {
		var ret string
		return ret
	}
	return *o.SerialNumber
}

// GetSerialNumberOk returns a tuple with the SerialNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Motherboard) GetSerialNumberOk() (*string, bool) {
	if o == nil || IsNil(o.SerialNumber) {
		return nil, false
	}
	return o.SerialNumber, true
}

// HasSerialNumber returns a boolean if a field has been set.
func (o *Motherboard) HasSerialNumber() bool {
	if o != nil && !IsNil(o.SerialNumber) {
		return true
	}

	return false
}

// SetSerialNumber gets a reference to the given string and assigns it to the SerialNumber field.
func (o *Motherboard) SetSerialNumber(v string) {
	o.SerialNumber = &v
}

func (o Motherboard) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Motherboard) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Vendor) {
		toSerialize["vendor"] = o.Vendor
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.SerialNumber) {
		toSerialize["serial_number"] = o.SerialNumber
	}
	return toSerialize, nil
}

type NullableMotherboard struct {
	value *Motherboard
	isSet bool
}

func (v NullableMotherboard) Get() *Motherboard {
	return v.value
}

func (v *NullableMotherboard) Set(val *Motherboard) {
	v.value = val
	v.isSet = true
}

func (v NullableMotherboard) IsSet() bool {
	return v.isSet
}

func (v *NullableMotherboard) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMotherboard(val *Motherboard) *NullableMotherboard {
	return &NullableMotherboard{value: val, isSet: true}
}

func (v NullableMotherboard) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMotherboard) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


